### ISSUE TITLE
provide some logging information while running

### ISSUE THREAD

**Issue by SophieHerbst** [hoechenberger/mne-bids-pipeline-extensions#2]
Currently no information is provided. Nice to have would be:
- number of participants, contrasts
- successful exit message
- pointer to results

**Comment by hoechenberger** [comment]
I'm actually surprised we didn't see output on your computer. Because we DO emit log messages and I see them on my machine! Check the code for `logger`. @agramfort any idea why log messages might not appear for @SophieHerbst? The script is using the MNE logger

**Comment by agramfort** [comment]
@SophieHerbst can you paste me the content of this file `~/.mne/mne-python.json` on your machine. In particular what is the value of `MNE_LOGGING_LEVEL`

**Comment by SophieHerbst** [comment]
@agramfort @hoechenberger  I cannot find the logging level in the file:
(paths are missing because I removed them)
{
"MNE_BROWSE_RAW_SIZE": "20.0,11.927083333333334",
"MNE_COREG_ADVANCED_RENDERING": "true",
"MNE_COREG_COPY_ANNOT": "true",
"MNE_COREG_GUESS_MRI_SUBJECT": "true",
"MNE_COREG_HEAD_HIGH_RES": "true",
"MNE_COREG_HEAD_INSIDE": "true",
"MNE_COREG_HEAD_OPACITY": "1.0",
"MNE_COREG_INTERACTION": "trackball",
"MNE_COREG_MARK_INSIDE": "true",
"MNE_COREG_ORIENT_TO_SURFACE": "false",
"MNE_COREG_PREPARE_BEM": "true",
"MNE_COREG_PROJECT_EEG": "false",
"MNE_COREG_SCALE_BY_DISTANCE": "false",
"MNE_COREG_SCALE_LABELS": "true",
"MNE_COREG_SCENE_SCALE": "0.18491239987569688",
"MNE_COREG_SUBJECTS_DIR": "",
"MNE_COREG_WINDOW_HEIGHT": "995",
"MNE_COREG_WINDOW_WIDTH": "1680",
"MNE_DATASETS_EEGBCI_PATH": "",
"MNE_DATASETS_FIELDTRIP_CMC_PATH": "",
"MNE_DATASETS_KILOWORD_PATH": "",
"MNE_DATASETS_SAMPLE_PATH": "/volatile",
"MNE_DATASETS_SOMATO_PATH": "",
"SUBJECTS_DIR": ""
}
}

**Comment by SophieHerbst** [comment]
Actually it says mne.set_log_level("warning") in the source_contrast.py file 🤪

**Comment by hoechenberger** [comment]
Oh. Maybe I put this in for debugging at some point 😅 ok then now we know how to fix things :) 

The idea would maybe be to keep the log level for MNE at warning and use a separate (custom) logger for our output here, so that we can log with a level of "info"
