### ISSUE TITLE
RuntimeWarning: Something went wrong in the data-driven estimation of the data rank

### ISSUE THREAD

**Issue by SophieHerbst** [hoechenberger/mne-bids-pipeline-extensions#6]
Now that I can see the warnings, I fear that there is something wrong with the ranks again. Didn't we fix that last time?
`
RuntimeWarning: Something went wrong in the data-driven estimation of the data rank as it exceeds the theoretical rank from the info (306 > 70). Consider setting rank to "auto" or setting it explicitly as an integer.`

**Comment by hoechenberger** [comment]
When we tried out the code together we passed rank="info" somewhere, which wasn't in the original script back then. We need to find out where we added this and need to add it back. Wanna give it a shot?
